# yaml-language-server: $schema=https://coderabbit.ai/integrations/coderabbit-overrides.v2.json
language: "en"
chat: 
  auto_reply: true
reviews:
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: true
  path_filters: 
    - "!**/*.hs"
    - "!**/*.sqlite"
  auto_review:
    enabled: true
    ignore_title_keywords:
    - "WIP"
    - "Draft"
    drafts: false
    base_branches: []
    labels: []