version: "3.9"
services:
  plutus-certification-web:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - REACT_APP_BASE_URL=https://google.com:8080
    ports:
      - "3000:3000"
