FROM node:16

WORKDIR /app/
COPY react-web /app
COPY ./docker-files/.env.local .
RUN npm install

#"homepage": "https://input-output-hk.github.io/dapps-certification/"
RUN sed -i 's/https:\/\/input-output-hk.github.io\/dapps-certification/http:\/\/localhost:3000/g' package.json
#"proxy": "https://testing.dapps.iog.io/"
RUN sed -i 's/https:\/\/testing.dapps.iog.io/http:\/\/localhost:3000/g'  package.json

COPY ./docker-files/start_web.sh .
RUN chmod +x ./start_web.sh

ENTRYPOINT [ "./start_web.sh" ]
#ENTRYPOINT [ "/bin/sh","-c","./start_web.sh"]
CMD [ "npm","start" ]
