FROM node:16

RUN git clone https://github.com/input-output-hk/dapps-certification.git
RUN mv dapps-certification app
WORKDIR /app/
RUN git checkout develop
WORKDIR /app/react-web
COPY ./docker-files/.env.local .
RUN yarn install

#"proxy": "https://testing.dapps.iog.io/"
#"homepage": "https://input-output-hk.github.io/dapps-certification/"

#/dapps-certification/"
RUN sed -i 's/https:\/\/input-output-hk.github.io/http:\/\/localhost:3000/g' package.json
RUN sed -i 's/https:\/\/testing.dapps.iog.io/http:\/\/localhost:3000/g'  package.json

#ENTRYPOINT [ "/bin/sh" ]
CMD [ "yarn","start" ]
