name: CI Tests
on: 
  push: 
  pull_request:
  workflow_call: # as ci-tests.yml is called from ci-deploy.yml as a dependency
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - run: |
          cd react-web
          npm ci
          npm run test